package com.wrkhalil.learningthroughlistening.Model;

import android.content.Context;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;

public class SRTFile {

    //Attributes
    private String id;
    private List<String> parsedTranscript;
    private List<String> generatedTranscript;
    private String path;

    //SRTFile Constructor
    SRTFile(String id, List<String> parsedTranscript, List<String> generatedTranscript){
        this.id = id; //Fetch id
        this.parsedTranscript = parsedTranscript; //Fetch parsedTranscript
        this.generatedTranscript = generatedTranscript; //Fetch generatedTranscript
        generateClosedCaptions(); //Executed to merge the parsedTranscript and generatedTranscript
        writeToFile(BaseApplication.getAppContext()); //Executed to write the new closed captions to a .SRT file
    }

    //Executed to merge the parsedTranscript and generatedTranscript
    private void generateClosedCaptions(){
        int generatedTranscriptIndex = 0;
        for (int i = 0 ; i < parsedTranscript.size() ; i++){
            //Leave the timestamps and replace the lyrics with the new lyrics generated by the app
            if (parsedTranscript.get(i).charAt(0) == generatedTranscript.get(generatedTranscriptIndex).charAt(0)){
                parsedTranscript.set(i, generatedTranscript.get(generatedTranscriptIndex));
                generatedTranscriptIndex ++;
            }
        }
    }

    //Executed to write the new closed captions to a .SRT file
    private void writeToFile(Context context) {
        String fileName = id + ".srt";
        String text;
        FileOutputStream fos = null;

        try {
            fos = context.openFileOutput(fileName, Context.MODE_PRIVATE);
            for (int i = 0 ; i < parsedTranscript.size() ; i++){
                text = (parsedTranscript.get(i)+'\n'); //Retrieve a line from the lyrics array list
                fos.write(text.getBytes()); //Write to the file
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            if (fos != null) {
                try {
                    fos.close();
                    path = context.getFilesDir() + "/" + fileName; //Retrieve the path if saving the .SRT file was successful and pass it to the player to display the lyrics
                } catch (IOException e) {
                    e.printStackTrace(); //Print the error stack if writing the file fails
                }
            }
        }
    }

    //Getters
    public String getPath() {
        return path;
    }


}
